export { default as Header1 } from './Header1'
export { default as Header2 } from './Header2'
export { default as Header3 } from './Header3'
export { default as Header4 } from './Header4'
export { default as Header5 } from './Header5'
export { default as Header6 } from './Header6'